#!/usr/bin/env bash
# configuring web-01 to have an HTTP response header

#updating packages
sudo apt-get update
sudo apt-get install -y nginx

#creating an index page
echo "Hello World!" | sudo tee /var/www/html/index.html

#preforming a redirection
new = "server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"

sudo sed -i "s/server_name _;/Snew/" /etc/nginx/sites-enabled/default

#creating a custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

#custom HTTP response header
sudo sed -i "server_name _;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

#test for syntax errors
sudo nginx -t

#restart nginx
sudo service nginx restart
