#!/usr/bin/env bash
# Configures a Nginx server to listen on port 80

#remose the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
# Configure Nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-availeble/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
